services:  
    app:
        image: diovanegabriel/php8.3-laravel:latest
        container_name: agro-php
        ports:
            - 8081:80
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        volumes:
            - ./:/var/www/html
            - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
        restart: unless-stopped
        networks:
            agro:

networks:
    agro:
        external: true